// Generated by CoffeeScript 1.8.0
(function() {
  var SnowyLoader;

  SnowyLoader = (function() {
    function SnowyLoader() {}

    SnowyLoader.prototype.createCanvas = function(name) {
      var s, t;
      s = document.createElement('canvas');
      s.id = name;
      s.style.position = 'absolute';
      s.style.zIndex = 100;
      s.style.top = 0;
      s.style.left = 0;
      s.style.pointerEvents = 'none';
      t = document.body;
      return t.appendChild(s);
    };

    SnowyLoader.prototype.setScript = function(src, tag) {
      var s, t;
      s = document.createElement('script');
      s.type = 'text/javascript';
      s.src = src;
      t = document.querySelector(tag);
      return t.appendChild(s);
    };

    return SnowyLoader;

  })();

  document.addEventListener('DOMContentLoaded', function() {
    var cjs, initSnowy, l;
    l = new SnowyLoader;
    l.createCanvas('snowyCanvas');
    cjs = l.setScript('http://code.createjs.com/createjs-2014.12.12.min.js', 'head');
    cjs.onload = function() {
      var sb;
      sb = l.setScript('snowybase.js', 'head');
      return sb.onload = function() {
        return initSnowy();
      };
    };
    return initSnowy = function() {
      var s;
      return s = new Snowy('snowyCanvas');
    };
  });

}).call(this);
