// Generated by CoffeeScript 1.8.0
(function() {
  var Flake, Snowy,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  Flake = (function() {
    function Flake() {
      this.initialize();
    }

    Flake.prototype = new createjs.Container;

    Flake.prototype.Container_initialize = Flake.prototype.initialize;

    Flake.prototype.initialize = function() {
      var b, bf, g, s;
      this.Container_initialize();
      g = new createjs.Graphics();
      g.beginFill('white');
      g.drawCircle(0, 0, 5);
      s = new createjs.Shape(g);
      bf = new createjs.BlurFilter(5, 5, 1);
      s.filters = [bf];
      b = bf.getBounds();
      s.cache(-5 + b.x, -5 + b.y, 10 + b.width, 10 + b.height);
      this.xSpeed = 0;
      this.vel = 0;
      return this.addChild(s);
    };

    return Flake;

  })();

  Snowy = (function() {
    var flakesNumber, speed;

    speed = 2;

    flakesNumber = 500;

    function Snowy(_name) {
      this.handleTick = __bind(this.handleTick, this);
      this.fall = __bind(this.fall, this);
      var flake, h, i, name, w, _i;
      name = _name != null ? _name : 'snowyCanvas';
      w = window.innerWidth;
      h = window.innerHeight;
      this.flakes = [];
      this.stage = new createjs.Stage(name);
      this.stage.canvas.width = w;
      this.stage.canvas.height = h;
      createjs.Ticker.setFPS(60);
      createjs.Ticker.addEventListener('tick', this.handleTick);
      for (i = _i = 0; 0 <= flakesNumber ? _i <= flakesNumber : _i >= flakesNumber; i = 0 <= flakesNumber ? ++_i : --_i) {
        flake = new Flake;
        flake.vel = Math.random() * speed + 0.5;
        flake.xSpeed = Math.random() * 90;
        flake.scaleX = (Math.random() * 1) + 0.3;
        flake.scaleY = flake.scaleX;
        flake.alpha = Math.random();
        flake.x = Math.random() * w;
        flake.y = 0;
        this.stage.addChild(flake);
        this.flakes.push(flake);
      }
      this.stage.update();
    }

    Snowy.prototype.fall = function() {
      var i, _i, _ref, _results;
      _results = [];
      for (i = _i = 0, _ref = this.flakes.length; 0 <= _ref ? _i < _ref : _i > _ref; i = 0 <= _ref ? ++_i : --_i) {
        this.flakes[i].xSpeed++;
        this.flakes[i].x += Math.sin(this.flakes[i].xSpeed / 25);
        this.flakes[i].y += this.flakes[i].vel;
        if (this.flakes[i].y > this.stage.canvas.height) {
          this.flakes[i].x = Math.random() * this.stage.canvas.width;
          _results.push(this.flakes[i].y = 0);
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    Snowy.prototype.handleTick = function() {
      this.fall();
      return this.stage.update();
    };

    window.Snowy = Snowy;

    return Snowy;

  })();

}).call(this);
